### ISSUE TITLE
ItemPredicateParser doesn't support EcoEnchants

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/StorageQuery#1]
```
[15:02:06 INFO]: [ItemPredicateParser] Downloading language-file en_us
[15:02:10 ERROR]: [ItemPredicateParser] Could not download and or initialize languages
java.lang.IllegalStateException: Could not locate translation-value for key enchantment.minecraft.wound
        at ItemPredicateParser-0.0.1.jar/me.blvckbytes.item_predicate_parser.translation.TranslationRegistry.createEntries(TranslationRegistry.java:96) ~[ItemPredicateParser-0.0.1.jar:?]
        at ItemPredicateParser-0.0.1.jar/me.blvckbytes.item_predicate_parser.translation.TranslationRegistry.initialize(TranslationRegistry.java:36) ~[ItemPredicateParser-0.0.1.jar:?]
        at ItemPredicateParser-0.0.1.jar/me.blvckbytes.item_predicate_parser.translation.LanguageRegistry.initializeTranslationRegistry(LanguageRegistry.java:87) ~[ItemPredicateParser-0.0.1.jar:?]
        at ItemPredicateParser-0.0.1.jar/me.blvckbytes.item_predicate_parser.translation.LanguageRegistry.<init>(LanguageRegistry.java:46) ~[ItemPredicateParser-0.0.1.jar:?]
        at ItemPredicateParser-0.0.1.jar/me.blvckbytes.item_predicate_parser.ItemPredicateParserPlugin.onEnable(ItemPredicateParserPlugin.java:24) ~[ItemPredicateParser-0.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[15:02:10 INFO]: [ItemPredicateParser] Disabling ItemPredicateParser v0.1
```
The key `enchantment.minecraft.wound` is From EcoEnchants  
https://github.com/Auxilor/EcoEnchants

**Comment by BlvckBytes** [comment]
The latest version should now allow to query for enchantments stemming from EcoEnchants. Please give it a try! :)
