### ISSUE TITLE
1.20.4 Paper issue

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/StorageQuery#10]
doesn't work in 1.20.4 Paper
```
[15:25:17 INFO]: [ItemPredicateParser] Enabling ItemPredicateParser v0.0.10
[15:25:17 INFO]: [ItemPredicateParser] Created folder to house language files
[15:25:17 INFO]: [ItemPredicateParser] Detected version >= 1.20
[15:25:17 INFO]: [ItemPredicateParser] Downloading language-file en_us
[15:25:20 INFO]: [ItemPredicateParser] Loaded 1398 entries for language en_us
[15:25:20 INFO]: [ItemPredicateParser] Downloading language-file en_gb
[15:25:21 INFO]: [ItemPredicateParser] Loaded 1398 entries for language en_gb
[15:25:21 INFO]: [ItemPredicateParser] Downloading language-file zh_cn
[15:25:21 INFO]: [ItemPredicateParser] Loaded 1398 entries for language zh_cn
[15:25:21 INFO]: [ItemPredicateParser] Downloading language-file de_de
[15:25:21 INFO]: [ItemPredicateParser] Loaded 1398 entries for language de_de
[15:25:21 INFO]: [ItemPredicateParser] Downloading language-file de_at
[15:25:21 INFO]: [ItemPredicateParser] Loaded 1398 entries for language de_at
[15:25:21 INFO]: [ItemPredicateParser] Downloading language-file de_ch
[15:25:21 INFO]: [ItemPredicateParser] Loaded 1398 entries for language de_ch
[31;1m[15:25:21 ERROR]: [ItemPredicateParser] Could not download and or initialize languages
java.lang.IllegalStateException: Could not locate the CraftServer class
        at me.blvckbytes.bukkitevaluable.CommandUpdater.locateCraftServerClass(CommandUpdater.java:126) ~[ItemPredicateParser-0.0.10.jar:?]
        at me.blvckbytes.bukkitevaluable.CommandUpdater.<init>(CommandUpdater.java:32) ~[ItemPredicateParser-0.0.10.jar:?]
        at me.blvckbytes.item_predicate_parser.ItemPredicateParserPlugin.onEnable(ItemPredicateParserPlugin.java:33) ~[ItemPredicateParser-0.0.10.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R4.CraftServer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:421) ~[?:?]
        at java.lang.Class.forName(Class.java:412) ~[?:?]
        at me.blvckbytes.bukkitevaluable.CommandUpdater.locateCraftServerClass(CommandUpdater.java:124) ~[ItemPredicateParser-0.0.10.jar:?]
        ... 14 more
[m[15:25:21 INFO]: [ItemPredicateParser] Disabling ItemPredicateParser v0.0.10
```

**Comment by YuanYuanOwO** [comment]
same in 1.20.6
```
[15:27:01 INFO]: [ItemPredicateParser] Enabling ItemPredicateParser v0.0.10
[15:27:01 INFO]: [ItemPredicateParser] Created folder to house language files
[15:27:01 INFO]: [ItemPredicateParser] Detected version >= 1.20
[15:27:02 INFO]: [ItemPredicateParser] Downloading language-file en_us
[15:27:04 INFO]: [ItemPredicateParser] Loaded 1425 entries for language en_us
[15:27:04 INFO]: [ItemPredicateParser] Downloading language-file en_gb
[15:27:05 INFO]: [ItemPredicateParser] Loaded 1425 entries for language en_gb
[15:27:05 INFO]: [ItemPredicateParser] Downloading language-file zh_cn
[15:27:05 INFO]: [ItemPredicateParser] Loaded 1425 entries for language zh_cn
[15:27:05 INFO]: [ItemPredicateParser] Downloading language-file de_de
[15:27:05 INFO]: [ItemPredicateParser] Loaded 1425 entries for language de_de
[15:27:05 INFO]: [ItemPredicateParser] Downloading language-file de_at
[15:27:06 INFO]: [ItemPredicateParser] Loaded 1425 entries for language de_at
[15:27:06 INFO]: [ItemPredicateParser] Downloading language-file de_ch
[15:27:06 INFO]: [ItemPredicateParser] Loaded 1425 entries for language de_ch
[31;1m[15:27:06 ERROR]: [ItemPredicateParser] Could not download and or initialize languages
java.lang.IllegalStateException: Could not locate the CraftServer class
        at ItemPredicateParser-0.0.10.jar/me.blvckbytes.bukkitevaluable.CommandUpdater.locateCraftServerClass(CommandUpdater.java:126) ~[ItemPredicateParser-0.0.10.jar:?]
        at ItemPredicateParser-0.0.10.jar/me.blvckbytes.bukkitevaluable.CommandUpdater.<init>(CommandUpdater.java:32) ~[ItemPredicateParser-0.0.10.jar:?]
        at ItemPredicateParser-0.0.10.jar/me.blvckbytes.item_predicate_parser.ItemPredicateParserPlugin.onEnable(ItemPredicateParserPlugin.java:33) ~[ItemPredicateParser-0.0.10.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-78]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-78]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:609) ~[paper-1.20.6.jar:git-Paper-78]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:558) ~[paper-1.20.6.jar:git-Paper-78]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[paper-1.20.6.jar:git-Paper-78]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[paper-1.20.6.jar:git-Paper-78]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:git-Paper-78]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-78]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-78]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R6.CraftServer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.1.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.20.6.jar:git-Paper-78]
        at ItemPredicateParser-0.0.10.jar/me.blvckbytes.bukkitevaluable.CommandUpdater.locateCraftServerClass(CommandUpdater.java:124) ~[ItemPredicateParser-0.0.10.jar:?]
        ... 14 more
[m[15:27:06 INFO]: [ItemPredicateParser] Disabling ItemPredicateParser v0.0.10
```

**Comment by BlvckBytes** [comment]
Please check whether this issue still occurs within the [latest release](https://github.com/BlvckBytes/ItemPredicateParser/releases/tag/v0.0.11).

**Comment by YuanYuanOwO** [comment]
same issue

**Comment by BlvckBytes** [comment]
Are you sure that you loaded the newest version? The `CraftServer`-related exception should not be possible in the same way anymore.

**Comment by YuanYuanOwO** [comment]
oops
wait a sec
