### ISSUE TITLE
ItemPredicateParser doesn't support 3rd-party enchant plugin

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/StorageQuery#7]
As in the case mentioned in #1, even though compatibility support is added separately for EcoEnchants, it seems that other plugins get the same error, and it would be tiresome to add separate support for most plugins i think  
In fact, I think it might not be just enchantment plugins that have this problem, but other types of plugins as well perhaps  
```
[20:15:04 ERROR]: [ItemPredicateParser] Could not download and or initialize languages
java.lang.IllegalStateException: Could not locate translation-value for key enchantment.minecraft.poisoned_arrows
        at ItemPredicateParser-0.0.7 (1).jar/me.blvckbytes.item_predicate_parser.translation.TranslationRegistry.createEntries(TranslationRegistry.java:111) ~[ItemPredicateParser-0.0.7 (1).jar:?]
        at ItemPredicateParser-0.0.7 (1).jar/me.blvckbytes.item_predicate_parser.translation.TranslationRegistry.initialize(TranslationRegistry.java:47) ~[ItemPredicateParser-0.0.7 (1).jar:?]
        at ItemPredicateParser-0.0.7 (1).jar/me.blvckbytes.item_predicate_parser.translation.LanguageRegistry.initializeTranslationRegistry(LanguageRegistry.java:91) ~[ItemPredicateParser-0.0.7 (1).jar:?]
        at ItemPredicateParser-0.0.7 (1).jar/me.blvckbytes.item_predicate_parser.translation.LanguageRegistry.<init>(LanguageRegistry.java:50) ~[ItemPredicateParser-0.0.7 (1).jar:?]
        at ItemPredicateParser-0.0.7 (1).jar/me.blvckbytes.item_predicate_parser.ItemPredicateParserPlugin.onEnable(ItemPredicateParserPlugin.java:41) ~[ItemPredicateParser-0.0.7 (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
This key is from https://github.com/nulli0n/ExcellentEnchants-spigot

**Comment by BlvckBytes** [comment]
Right, I see - thank you for letting me know! I can easily add support for as many plugins as there are, as long as they provide an API which lets me retrieve the display-name of what they add to the `Registry`. But I see what you're getting at: I should probably stop throwing an actual exception, but rather only log a warning-message, to let the user know that they are potentially missing out on some entries which cannot be accessed by the parser.

**Comment by BlvckBytes** [comment]
The [latest release](https://github.com/BlvckBytes/ItemPredicateParser/releases/tag/v0.0.8) should now support ExcellentEnchants, and will no longer throw and thereby disable the plugin if a key cannot be located. Please once again test it locally, :).

**Comment by YuanYuanOwO** [comment]
Seems to be fine, thanks for your amazing work
