### ISSUE TITLE
1.19.4 paper issue

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/StorageQuery#8]
Doesn't work in 1.19.4 Paper
```
[15:18:22] [Server thread/INFO]: [ItemPredicateParser] Enabling ItemPredicateParser v0.0.10
[15:18:22] [Server thread/INFO]: [ItemPredicateParser] Extended 1 new keys on the configuration config.yml
[15:18:22] [Server thread/INFO]: [ItemPredicateParser] Detected version < 1.20
[15:18:22] [Server thread/ERROR]: [ItemPredicateParser] Could not download and or initialize languages
java.lang.IllegalStateException: Couldn't locate valid key for Material NETHERITE_UPGRADE_SMITHING_TEMPLATE
	at me.blvckbytes.item_predicate_parser.translation.keyed.LangKeyedItemMaterial.<init>(LangKeyedItemMaterial.java:30) ~[ItemPredicateParser-0.0.10.jar:?]
	at me.blvckbytes.item_predicate_parser.translation.version.VersionDependentCode_LT_1_20.lambda$getItemMaterials$0(VersionDependentCode_LT_1_20.java:40) ~[ItemPredicateParser-0.0.10.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at me.blvckbytes.item_predicate_parser.translation.version.VersionDependentCode_LT_1_20.getItemMaterials(VersionDependentCode_LT_1_20.java:40) ~[ItemPredicateParser-0.0.10.jar:?]
	at me.blvckbytes.item_predicate_parser.translation.LanguageRegistry.makeSources(LanguageRegistry.java:109) ~[ItemPredicateParser-0.0.10.jar:?]
	at me.blvckbytes.item_predicate_parser.translation.LanguageRegistry.initializeTranslationRegistry(LanguageRegistry.java:91) ~[ItemPredicateParser-0.0.10.jar:?]
	at me.blvckbytes.item_predicate_parser.translation.LanguageRegistry.<init>(LanguageRegistry.java:50) ~[ItemPredicateParser-0.0.10.jar:?]
	at me.blvckbytes.item_predicate_parser.ItemPredicateParserPlugin.onEnable(ItemPredicateParserPlugin.java:30) ~[ItemPredicateParser-0.0.10.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[15:18:22] [Server thread/INFO]: [ItemPredicateParser] Disabling ItemPredicateParser v0.0.10
```

**Comment by BlvckBytes** [comment]
Please check whether this issue still occurs within the [latest release](https://github.com/BlvckBytes/ItemPredicateParser/releases/tag/v0.0.11).
