### ISSUE TITLE
1.20.1 Paper issue

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/StorageQuery#9]
doesn't work in 1.20.1 paper
```
[15:23:34 INFO]: [ItemPredicateParser] Enabling ItemPredicateParser v0.0.10
[15:23:34 INFO]: [ItemPredicateParser] Created folder to house language files
[15:23:34 INFO]: [ItemPredicateParser] Detected version >= 1.20
[15:23:34 INFO]: [ItemPredicateParser] Downloading language-file en_us
[31;1m[15:23:36 ERROR]: [ItemPredicateParser] Could not download and or initialize languages
java.lang.NoSuchFieldError: Class org.bukkit.Registry does not have member field 'org.bukkit.Registry EFFECT'
        at me.blvckbytes.item_predicate_parser.translation.version.VersionDependentCode_GTE_1_20.getEffects(VersionDependentCode_GTE_1_20.java:30) ~[ItemPredicateParser-0.0.10.jar:?]
        at me.blvckbytes.item_predicate_parser.translation.LanguageRegistry.makeSources(LanguageRegistry.java:104) ~[ItemPredicateParser-0.0.10.jar:?]
        at me.blvckbytes.item_predicate_parser.translation.LanguageRegistry.initializeTranslationRegistry(LanguageRegistry.java:91) ~[ItemPredicateParser-0.0.10.jar:?]
        at me.blvckbytes.item_predicate_parser.translation.LanguageRegistry.<init>(LanguageRegistry.java:50) ~[ItemPredicateParser-0.0.10.jar:?]
        at me.blvckbytes.item_predicate_parser.ItemPredicateParserPlugin.onEnable(ItemPredicateParserPlugin.java:30) ~[ItemPredicateParser-0.0.10.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[m[15:23:36 INFO]: [ItemPredicateParser] Disabling ItemPredicateParser v0.0.10
```

**Comment by BlvckBytes** [comment]
Please check whether this issue still occurs within the [latest release](https://github.com/BlvckBytes/ItemPredicateParser/releases/tag/v0.0.11).
